app/src/Entity/Delivery.php
<?php

namespace App\Entity;

use App\Repository\DeliveryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DeliveryRepository::class)
 */
class Delivery
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $Address;

    /**
     * @ORM\Column(type="integer")
     */
    private $home_number;

    /**
     * @ORM\Column(type="integer")
     */
    private $flat;

    /**
     * @ORM\OneToOne(targetEntity=Order::class, inversedBy="delivery", cascade={"persist", "remove"})
     */
    private $rel_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $City;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getHomeNumber(): ?int
    {
        return $this->home_number;
    }

    public function setHomeNumber(int $home_number): self
    {
        $this->home_number = $home_number;

        return $this;
    }

    public function getFlat(): ?int
    {
        return $this->flat;
    }

    public function setFlat(int $flat): self
    {
        $this->flat = $flat;

        return $this;
    }

    public function getRelOrder(): ?Order
    {
        return $this->rel_order;
    }

    public function setRelOrder(?Order $rel_order): self
    {
        $this->rel_order = $rel_order;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }
}

app/src/Controller/OrderlistController.php
<?php

namespace App\Controller;

use App\Entity\Delivery;
use App\Entity\Order;
use App\Entity\User;
use App\Form\OrderType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderlistController extends AbstractController
{
    /**
     * @Route("/orderlist", name="orderlist")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->findOneBy(['email'=>$this->getUser()->getUsername()]);

        $OrderSet = $user->getOrders();

        $orders=$paginator->paginate($OrderSet,$request->query

            ->getInt('page',1),10);

        return $this->render('orderlist/index.html.twig', [
            'controller_name' => 'OrderlistController',
            'orders' => $orders
        ]);
    }

    /**
     * @Route ("/orderlist/{slug}", name="order.detail")
     * @param Order $order
     * @param Request $request
     * @return Response
     */
    public function orderDetails(Order $order, Request $request):Response
    {
        return $this->render('orderlist/order_show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route ("/orderlist/{slug}/delivery", name="order.detail.delivery")
     * @param Order $order
     * @param Request $request
     * @return Response
     */
    public function deliveryDetails(Order $order, Request $request):Response
    {
        $processingTime =(date_diff( new \DateTime("now") , $order->getUpdatedAt()));

        return $this->render('orderlist/delivery.html.twig', [
            'delivery' => $order->getDelivery(),
            'processing' =>$processingTime->format(" days: %a: hours: %h:%i:%s"),
        ]);
    }
}

app/templates/orderlist/delivery.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<style>

    article {
        background-color: RGB(249, 255, 16); /* Цвет фона под заголовком */
        max-width: 600px;
    }
    input {
        border-radius: 10px;
    }

</style>
    <div class="row mt-4">
        <h2>{{ delivery.relOrder.slug }}</h2>
    </div>

    <div class="row mt-4">
<article class="well" >
    <h2>Delivery Info</h2>
    <h5>In transit:</h5>
    <p>{{ processing}}</p>
    <h5>City</h5>
    <p>{{ delivery.city}}</p>
    <h5>street</h5>
    <p>{{ delivery.address }}</p>
    <h5>home number</h5>
    <p>{{ delivery.homeNumber }}</p>
    <h5>flat</h5>
    <p>{{ delivery.flat }}</p>
</article>
        <a href="{{ path('orderlist')}}" class="btn btn-default w-100">BACK</a>
    </div>
{% endblock %}

app/templates/orderlist/index.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'blog_index' %}

{% block main %}
    <h2>Order history</h2>
    {% for order in orders %}
        <article class="well">
            <h2>
                <a href = "{{ path('order.detail', {slug: order.slug}) }}">
                    {{ order.slug }}
                </a>
                <p>{{order.total}}</p>
            </h2>
        </article>
    {% else %}
        <div class="well">no orders found</div>
    {% endfor %}

    <div class="navigation text-center">
        {{ knp_pagination_render(orders)}}
    </div>
{% endblock %}

{% block sidebar %}
{% endblock %}

app/templates/orderlist/order_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Order: {{ order.slug }}</h1>

        {% if order.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            {% for item in order.items %}
                                <li class="list-group-item d-flex">
                                    <div class="flex-fill mr-2">
                                        <img src="https://via.placeholder.com/200x150" width="64" alt="Product image">
                                    </div>
                                    <div class="flex-fill mr-2">

                                        <a href="{{ path('product.detail', {slug: item.product.slug}) }}">
                                            <h3 class="mt-0 mb-0">{{ item.product.name }}</h3>
                                        </a>

                                        <small>{{ item.product.description[:50] }}...</small>
                                        <div class="form-inline mt-2">
                                            <p> Quantity: {{ item.quantity }}</p>
                                        </div>
                                    </div>
                                    <div class="flex-fill mr-2 text-right">
                                        <b>{{ item.product.price }} €</b>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <!-- Summary -->
                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h3 class="card-header bg-dark text-white">Summary</h3>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>{{ order.total }} €</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            <a href="{{path('order.detail.delivery', {slug: order.slug}) }}" class="btn btn-info faw-100">
                                <i class="fa fa-cart"></i>DELIVERY INFO
                            </a>
                            <a href="{{ path('orderlist')}}" class="btn btn-default w-100">BACK</a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-info">
                You made no orders yet. Go to the <a href="{{ path('product_index') }}">product list</a>.
            </div>
        {% endif %}
    </div>
{% endblock %}